### ISSUE TITLE
Title overlaps itself on small screens

### ISSUE THREAD

**Issue by nbeloglazov** [the-development/flex#3]
1. Go to http://the-development.github.io/flex/ 
2. Resize browser making it very narrow. 
3. Title "EXAMPLE POST" is splitted into 2 lines due to narrow screen. But "POST" overlaps "EXAMPLE" creating bad visual experience.

I fixed on my website adding following css style: 

``` css
#title {
  line-height: 1em;
}
```

**Comment by ghost** [comment]
Thanks for letting me know -- before I commit the fix you suggested, just wanted to check for more possible issues:

The visual bug doesn't happen on my end unless the sidebar is also open. Is that the case with you too? 

Also, it seems like you're suggesting as soon as you make the browser narrow, the sidebar's open (should be collapsed/closed). That's not the case is it?

**Comment by nbeloglazov** [comment]
I think it depends on how long is title:
http://imgur.com/2q7FuXk&lnKv003
and
http://imgur.com/2q7FuXk&lnKv003#1

Actually even on normal screen the title overlaps if it is too long.

**Comment by ghost** [comment]
Gotcha, thanks for the screenshots! I'll fix responsiveness in the next little bit :)
